models_path: "output/models"

includes:
  - "../Lithium/src/Lithium/Renderer/ShaderInterop"
  - "../Article/src/Article/Rendering/ShaderInterop"

packs:
  - ["preload.yaml", "output/preload.lpack"]
  - ["resources.yaml", "output/resources.lpack"]
